version: '3.8'

services:
  app:
    build: .
    container_name: hrms_app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb+srv://syedsaqlain46:kahani3777@cluster0.fhldezx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: 9dU!23Fq@#kd*LxqZ^6mZ0aR
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: hrms_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
